# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4123922ccfe020caa6860a606cccde8e109c2c7f0ac6a5aa5f2eed192882c776aa82cfa44b87e58f5061f45e88da08d1da5c607d1acbc80dbe51551fe01c1202

test:
  secret_key_base: 5526d3002f2d014b5ed59a241544b14eb917f91abb94eb41f3dcac87e9e01f1af4a37e6033c8e4fbbdd95502aa36df3097ada2e05933008bcb1efa4f0b02857d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
